-- Baseline schema for the SCC poultry database.
--
-- Generated from the live schema that holds production data. Existing
-- databases are marked as already at this version via
-- spring.flyway.baseline-on-migrate, so this script only ever runs
-- against an empty schema (a fresh dev or CI database).
--
-- Do not edit this file: Flyway checksums applied migrations. Schema
-- changes belong in a new V2__, V3__ ... script.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `city` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `route_id` bigint NOT NULL,
  `obsolete` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKgcy03duvm2nxxj82sa5isgxk6` (`route_id`),
  CONSTRAINT `FKgcy03duvm2nxxj82sa5isgxk6` FOREIGN KEY (`route_id`) REFERENCES `route` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `customer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `city_id` bigint NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `mobile_no` varchar(255) DEFAULT NULL,
  `shop_name` varchar(255) DEFAULT NULL,
  `balance_amount` double NOT NULL,
  `obsolete` bit(1) NOT NULL,
  `credit_limit` double DEFAULT NULL,
  `credit_limit_enabled` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKt79b5wvqbf38jtkjx36vp9vam` (`city_id`),
  CONSTRAINT `FKt79b5wvqbf38jtkjx36vp9vam` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `customer_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `credit_amount` double NOT NULL,
  `debit_amount` double NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `is_backdated` bit(1) NOT NULL,
  `payment_mode` varchar(255) DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `reference_type` varchar(255) DEFAULT NULL,
  `running_balance` double NOT NULL,
  `transaction_date` date NOT NULL,
  `transaction_type` enum('OPENING_BALANCE','SALE','PAYMENT','CREDIT_NOTE','DEBIT_NOTE','ADJUSTMENT') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `customer_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKj7x9wtgx52d869egxusw0ypk9` (`customer_id`),
  CONSTRAINT `FKj7x9wtgx52d869egxusw0ypk9` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `customer_payment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` double NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `payment_date` date NOT NULL,
  `payment_mode` varchar(255) NOT NULL,
  `received_by` varchar(255) DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `transaction_reference` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `customer_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKj2oc6atfed430p54cpxeswcun` (`customer_id`),
  CONSTRAINT `FKj2oc6atfed430p54cpxeswcun` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `dc_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` double DEFAULT NULL,
  `dc_no` varchar(255) DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `kilograms` varchar(255) DEFAULT NULL,
  `nos` varchar(255) DEFAULT NULL,
  `rate` varchar(255) DEFAULT NULL,
  `purchase_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKlqfmotqxxhjhph0q0l4oyu7qs` (`purchase_id`),
  CONSTRAINT `FKlqfmotqxxhjhph0q0l4oyu7qs` FOREIGN KEY (`purchase_id`) REFERENCES `purchase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `driver` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `mobile_no` varchar(255) DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `parties` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `address` varchar(255) DEFAULT NULL,
  `balance_amount` int DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `is_obsolete` bit(1) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `owner` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `party_vehicles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `is_obsolete` bit(1) DEFAULT NULL,
  `vehicle_number` varchar(255) NOT NULL,
  `party_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_jsfl6vuwrtrlxu9mup466mw93` (`vehicle_number`),
  KEY `FK8p99rhwj9kib0dw84r8tg0o70` (`party_id`),
  CONSTRAINT `FK8p99rhwj9kib0dw84r8tg0o70` FOREIGN KEY (`party_id`) REFERENCES `parties` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `payment_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `closing_balance` int NOT NULL DEFAULT '0',
  `created_at` datetime(6) DEFAULT NULL,
  `date` date NOT NULL,
  `description` text,
  `opening_balance` int NOT NULL DEFAULT '0',
  `party_id` bigint NOT NULL,
  `payment` int NOT NULL,
  `transaction_id` varchar(100) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKpheydj5injubxr66i8jincnrm` (`party_id`),
  CONSTRAINT `FKpheydj5injubxr66i8jincnrm` FOREIGN KEY (`party_id`) REFERENCES `parties` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `purchase` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `branch` varchar(255) DEFAULT NULL,
  `diesel` varchar(255) DEFAULT NULL,
  `driver_expense` varchar(255) DEFAULT NULL,
  `entry_date` varchar(255) DEFAULT NULL,
  `farm` varchar(255) DEFAULT NULL,
  `hamali` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `paid_amount` double DEFAULT NULL,
  `supervisor_name` varchar(255) DEFAULT NULL,
  `supervisor_phone_no` varchar(255) DEFAULT NULL,
  `total_amount` double DEFAULT NULL,
  `driver_id` bigint DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `vehicle_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK2wrp358k6je2umx3kafwhy7t8` (`driver_id`),
  KEY `FK8omm6fki86s9oqk0o9s6w43h5` (`supplier_id`),
  KEY `FKtagphxgd35rlsr5of7mlfhk32` (`vehicle_id`),
  CONSTRAINT `FK2wrp358k6je2umx3kafwhy7t8` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`),
  CONSTRAINT `FK8omm6fki86s9oqk0o9s6w43h5` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FKtagphxgd35rlsr5of7mlfhk32` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `purchase_old` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` double DEFAULT NULL,
  `branch` varchar(255) DEFAULT NULL,
  `dc_file` varchar(255) DEFAULT NULL,
  `dc_no` varchar(255) DEFAULT NULL,
  `diesel` double DEFAULT NULL,
  `driver_expenses` double DEFAULT NULL,
  `entry_date` date DEFAULT NULL,
  `farm` varchar(255) DEFAULT NULL,
  `hamali` double DEFAULT NULL,
  `is_obsolute` bit(1) NOT NULL,
  `kilograms` double DEFAULT NULL,
  `nos` bigint DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `rate` bigint DEFAULT NULL,
  `supervisor_name` varchar(255) DEFAULT NULL,
  `supervisor_phone_no` bigint DEFAULT NULL,
  `driver_id` bigint NOT NULL,
  `supplier_id` bigint NOT NULL,
  `vehicle_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKhlyikhyu4urn55mbjo5541rgg` (`driver_id`),
  KEY `FKh1p46867f1wbisylcyga0yeh4` (`supplier_id`),
  KEY `FKmverwlqwmvm0tyg06yibm922m` (`vehicle_id`),
  CONSTRAINT `FKh1p46867f1wbisylcyga0yeh4` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FKhlyikhyu4urn55mbjo5541rgg` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`),
  CONSTRAINT `FKmverwlqwmvm0tyg06yibm922m` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `route` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `sale` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` int DEFAULT NULL,
  `birds` int DEFAULT NULL,
  `date` date DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `kilograms` double DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  `payment` int DEFAULT NULL,
  `payment_mode` varchar(255) DEFAULT NULL,
  `pending` int DEFAULT NULL,
  `rate` double DEFAULT NULL,
  `vehicle_no` bigint DEFAULT NULL,
  `customer_id` bigint NOT NULL,
  `driver_id` bigint NOT NULL,
  `route_id` bigint NOT NULL,
  `sale_details_id` bigint DEFAULT NULL,
  `balance_pending` int DEFAULT NULL,
  `sms_sent` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKjw88ojfoqquyd9f1obip1ar0g` (`customer_id`),
  KEY `FKjdaijiiie2jy5eahm0tr1vhsk` (`driver_id`),
  KEY `FKdumsv2r15rknqwysnljr0nehi` (`route_id`),
  KEY `FKe7gmfimgm4yrx2a0mfdmckg4y` (`sale_details_id`),
  CONSTRAINT `FKdumsv2r15rknqwysnljr0nehi` FOREIGN KEY (`route_id`) REFERENCES `route` (`id`),
  CONSTRAINT `FKe7gmfimgm4yrx2a0mfdmckg4y` FOREIGN KEY (`sale_details_id`) REFERENCES `sale_details` (`id`),
  CONSTRAINT `FKjdaijiiie2jy5eahm0tr1vhsk` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`),
  CONSTRAINT `FKjw88ojfoqquyd9f1obip1ar0g` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `sale_details` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `mortality` int DEFAULT NULL,
  `return_to_farm` int DEFAULT NULL,
  `total_amount` int DEFAULT NULL,
  `total_bird_sale` int DEFAULT NULL,
  `total_birds` int DEFAULT NULL,
  `total_kilogram_sale` int DEFAULT NULL,
  `total_payment_received` int DEFAULT NULL,
  `total_pending` int DEFAULT NULL,
  `driver_id` bigint NOT NULL,
  `route_id` bigint NOT NULL,
  `vehicle_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKssu3f8f38scbwus9jagc78g0i` (`driver_id`),
  KEY `FK8dm8bjrlx14u4vqiogklo8gdr` (`route_id`),
  KEY `FKqymq2msbu3hff93okm3co45nt` (`vehicle_id`),
  CONSTRAINT `FK8dm8bjrlx14u4vqiogklo8gdr` FOREIGN KEY (`route_id`) REFERENCES `route` (`id`),
  CONSTRAINT `FKqymq2msbu3hff93okm3co45nt` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicle` (`id`),
  CONSTRAINT `FKssu3f8f38scbwus9jagc78g0i` FOREIGN KEY (`driver_id`) REFERENCES `driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `supplier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `branch` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  `pending_payment` double DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `supplier_payment_hist` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `comment` varchar(255) DEFAULT NULL,
  `date_of_purchase` date DEFAULT NULL,
  `date_of_transaction` date DEFAULT NULL,
  `paid_amount` double DEFAULT NULL,
  `pending_payment` double DEFAULT NULL,
  `total_amount` double DEFAULT NULL,
  `trans_id` varchar(255) DEFAULT NULL,
  `purchase_id` bigint DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKju6syu4f0c6nwgfbnk71vovt9` (`purchase_id`),
  KEY `FK65u6b8p9s71yd57nhusv0adoe` (`supplier_id`),
  CONSTRAINT `FK65u6b8p9s71yd57nhusv0adoe` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FKju6syu4f0c6nwgfbnk71vovt9` FOREIGN KEY (`purchase_id`) REFERENCES `purchase` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `trading_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` int DEFAULT NULL,
  `balance_amount` int DEFAULT NULL,
  `birds` int DEFAULT NULL,
  `date` date DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `kilograms` double DEFAULT NULL,
  `payment` int DEFAULT NULL,
  `pending` int DEFAULT NULL,
  `rate` double DEFAULT NULL,
  `party_id` bigint NOT NULL,
  `party_vehicle_id` bigint NOT NULL,
  `supplier_id` bigint NOT NULL,
  `closing_balance` int NOT NULL DEFAULT '0',
  `created_at` datetime(6) DEFAULT NULL,
  `opening_balance` int NOT NULL DEFAULT '0',
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKld25iptfp0xubpijo570jhymq` (`party_id`),
  KEY `FK5gc2x9tp2h0vy2ns028pwlkk1` (`party_vehicle_id`),
  KEY `FKf861eg3eufi1qp571odoo8otp` (`supplier_id`),
  CONSTRAINT `FK5gc2x9tp2h0vy2ns028pwlkk1` FOREIGN KEY (`party_vehicle_id`) REFERENCES `party_vehicles` (`id`),
  CONSTRAINT `FKf861eg3eufi1qp571odoo8otp` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FKld25iptfp0xubpijo570jhymq` FOREIGN KEY (`party_id`) REFERENCES `parties` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `password` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `vehicle` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `pucdate` date DEFAULT NULL,
  `fitness_date` date DEFAULT NULL,
  `insurance_date` date DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `passing_date` date DEFAULT NULL,
  `vehicle_no` varchar(255) DEFAULT NULL,
  `obsolete` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


SET FOREIGN_KEY_CHECKS = 1;
