package com.app.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import lombok.Data;

/**
 * Who the business is, for anything the business sends out.
 *
 * The same six fields the frontend's companyConfig.js holds, now that documents are
 * also produced here: a statement generated by a scheduled job has no browser to read
 * that file from, and hard-coding the name and address in the renderer would leave two
 * places to change when the phone number does.
 *
 * Defaults are the real values rather than placeholders, so a statement is correct
 * without configuration and application.properties only has to carry an override.
 */
@Component
@ConfigurationProperties(prefix = "company")
@Data
public class CompanyProperties {

    private String name = "SOHEL CHICKEN CENTRE";
    private String shortName = "SOHEL";
    private String address = "Madha, Solapur, Maharashtra-413209";
    private String contactNumber = "+91 8605030099";
    private String email = "contact@sohelchickencentre.com";
    private String website = "www.sohelchickencentre.com";
}
